[book]
authors = ["HanchaiN"]
language = "en"
multilingual = false
src = "src"
title = "Lectures"

[build]
create-missing = true
extra-watch-dirs = ["scripts"]

[preprocessor.obsidian]
renderers = ["html"]
command = "python scripts/obsidian.py"

[preprocessor.tikzjax]
renderers = ["html"]
command = "python scripts/tikzjax.py"

[preprocessor.smiles-drawer]
renderers = ["html"]
command = "python scripts/smiles-drawer.py"

[preprocessor.mathjax-fix]
renderers = ["html"]
after = ["tikzjax"]
command = "python scripts/mathjax-fix.py"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
curly-quotes = true
mathjax-support = true
additional-css = [
	"theme/css/catppuccin.css",
	"theme/css/catppuccin-admonish.css"
]
additional-js = [
	"theme/js/whichlang.js",
	"theme/js/smilesDrawer.js",
	"theme/js/mermaid.min.js",
	"theme/js/mermaid-init.js"
]
no-section-label = true
git-repository-url = "https://github.com/HanchaiN/Lectures.git"
site-url = "https://hanchain.github.io/Lectures/"

[output.html.print]
enable = true

[output.html.fold]
enable = true

[output.html.search]
enable = true
