[book]
authors = ["HanchaiN"]
language = "en"
multilingual = false
src = "src"
title = "Lectures"

[build]
extra-watch-dirs = ["scripts"]

[preprocessor.tikzjax]
renderers = ["html"]
command = "python scripts/tikzjax.py"

[preprocessor.smiles-drawer]
renderers = ["html"]
command = "python scripts/smiles-drawer.py"

[preprocessor.mathjax-fix]
renderers = ["html"]
after = ["tikzjax"]
command = "python scripts/mathjax-fix.py"

[preprocessor.mathpunc]
before = ["katex"]
after = ["mathjax-fix"]

[preprocessor.katex]
renderers = ["html"]
after = ["links", "tikzjax", "mathjax-fix"]
output = "htmlAndMathml"
include-src = true
block-delimiter = { left = "<script type=\"text/tex\" data-type=\"block\">", right = "</script>" }
inline-delimiter = { left = "<script type=\"text/tex\" data-type=\"inline\">", right = "</script>" }

[preprocessor.wikilinks]

[output.html]
curly-quotes = true
mathjax-support = false
additional-css = [
	"theme/css/catppuccin.css",
	"theme/css/catppuccin-admonish.css"
]
additional-js = [
	"theme/js/whichlang.js",
	"theme/js/smilesDrawer.js"
]
no-section-label = true
git-repository-url = "https://github.com/HanchaiN/Lectures.git"
site-url = "https://hanchain.github.io/Lectures/"

[output.html.print]
enable = true

[output.html.fold]
enable = false

[output.html.search]
enable = true
