name: Export
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: vault
      - uses: actions/checkout@v4
        with:
          ref: docs
          token: ${{ secrets.GH_PAT }}
          path: docs
      - name: Install latest Obsidian Export
        run: |
          tag=$(curl 'https://api.github.com/repos/zoni/obsidian-export/releases/latest' | jq -r '.tag_name')
          url="https://github.com/zoni/obsidian-export/releases/download/${tag}/obsidian-export-installer.sh"
          curl --proto '=https' --tlsv1.2 -LsSf $url | sh
      - name: Export vault
        run: |
          rm -rf docs/src
          mkdir docs/src
          obsidian-export --frontmatter never ./vault docs/src
          cd docs
          git add src
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "deploy: update from ${GITHUB_SHA}" --allow-empty
          git push
