name: Export
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: vault
      - uses: actions/checkout@v4
        with:
          ref: docs
          token: ${{ secrets.GH_PAT }}
          path: docs
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Setup cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install latest obsidian-export
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: obsidian-export
      - name: Export vault
        run: |
          rm -rf docs/src
          mkdir docs/src
          obsidian-export --frontmatter never --no-recursive-embeds ./vault docs/src
          cd docs
          git add src
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "deploy: update from ${GITHUB_SHA}" --allow-empty
          git push
