name: Export
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: vault
      - use: actions/checkout@v3
        with:
          fetch-depth: 0
          path: docs
      - name: Install latest Obsidian Export
        run: |
          tag=$(curl 'https://api.github.com/repos/zoni/obsidian-export/releases/latest' | jq -r '.tag_name')
          url="https://github.com/zoni/obsidian-export/releases/download/${tag}/obsidian-export_Linux-x86_64.bin"
          mkdir bin
          curl -Lo bin/obsidian-export $url
          chmod +x bin/obsidian-export
      - name: Export vault
        run: |
          rm -rf docs/src
          mkdir docs/src
          ./bin/obsidian-export --frontmatter never --hard-linebreaks ./vault docs/src
          cd docs
          git add src
          git commit -m "deploy: update from ${GITHUB_SHA}"
          git push
